### ISSUE TITLE
CUDA version

### ISSUE THREAD

**Issue by boris-lapouga** [jonasrenault/adomvi#4]
What CUDA version did you use for this poetry dependencies? I've been trying from 12.2, 12.1 down to what's available on WSL2 which is 11.x, but it still doesn't work.

**Comment by jonasrenault** [comment]
As I mentioned [here](https://github.com/jonasrenault/adomvi/blob/6bfba796ffa1464c7f791a1994d402fe4a613525/adomvi/04_DreamboothFineTuning.ipynb#L33), I did run into some issues when installing the dependencies for the diffusers models with poetry. So if you're trying to run notebook [04_DreamboothFineTuning](https://github.com/jonasrenault/adomvi/blob/6bfba796ffa1464c7f791a1994d402fe4a613525/adomvi/04_DreamboothFineTuning.ipynb), i would recommend using a normal python env (i used mambaforge) to install the dependencies.
This is why I put the dependencies for diffusers in a dependency group in the pyproject.toml file, so you should probably be able to install only the base dependencies with poetry using `poetry install --without diffusers` if you only want to run the other notebooks.
Otherwise, the CUDA version i'm using is 12.1, but I'm not using WSL.
